### ISSUE TITLE
Containerization for dev-buddy : Dockerfile not working

### ISSUE THREAD

**Issue by shukra-in-spirit** [rog-golang-buddies/dev-buddy#3]
## ISSUE
I am getting the following error on running docker build.
```
supo@supo-GL63-9SD:~/GolandProjects/dev-buddy$ docker build . -t dev-buddy:v0.0.1
Sending build context to Docker daemon  849.9kB
Step 1/8 : FROM golang:1.18 as build
 ---> 2d952adaec1e
Step 2/8 : WORKDIR /go/src/app
 ---> Using cache
 ---> dcdc7227d0ad
Step 3/8 : COPY . .
 ---> 52bd90c81526
Step 4/8 : RUN mkdir -p /go/bin && CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/app ./...
 ---> Running in 864751813aad
go: downloading github.com/sethvargo/go-envconfig v0.8.0
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading golang.org/x/oauth2 v0.0.0-20220722155238-128564f6959c
go: downloading github.com/bwmarrin/discordgo v0.25.0
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading golang.org/x/crypto v0.0.0-20210421170649-83a5a9bb288b
go: downloading golang.org/x/net v0.0.0-20220624214902-1bab6f366d9e
go: downloading github.com/google/go-querystring v1.1.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/protobuf v1.28.0
go: cannot write multiple packages to non-directory /go/bin/app
The command '/bin/sh -c mkdir -p /go/bin && CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/app ./...' returned a non-zero code: 1
```
Can someone look into this? There might be multiple changes required in the Dockerfile.
There might be some ca certificate issue faced towards the end. Discordgo threw an x509 not verified error when I was working in a development container (golang: latest).
Helpful links for this: https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu https://stackoverflow.com/questions/51845690/how-to-program-go-to-use-a-proxy-when-using-a-custom-transport

## Acceptance Criteria:
docker build command should output an image for the dev buddy bot.

## Heads up
Three secrets will be required. For now you can use dummy values for them in your environment vars. We can collaborate on the testing part.: DISCORD_TOKEN="dummt-token", GITHUB_PAT="dummy-personal-access-token", GITHUB_OWNER="rog-golang-buddies"

**Comment by pallasite99** [comment]
To resolve this issue, you have a few options depending on your use case:

1. **Build a Single Binary:**
   If you intend to build a single Go binary, you should specify the exact entry point for your application (main package) instead of using `./...`.

   Assuming your main package is in the current directory, you can modify the Dockerfile with:

   ```Dockerfile
   FROM golang:latest

   WORKDIR /go/src/app

   # Copy the source code to the container's workspace
   COPY . .

   # Build the main package and output the binary to /go/bin/app
   RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/app
   ```

2. **Build Multiple Binaries:**
   If you have multiple Go packages in your project and you want to build each of them into separate binaries, you'll need to specify different output files for each binary. For example, if you have two packages, you can build them like this:

   ```Dockerfile
   FROM golang:latest

   WORKDIR /go/src/app

   # Copy the source code to the container's workspace
   COPY . .

   # Build the first package and output the binary to /go/bin/app1
   RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/app1 ./path/to/package1

   # Build the second package and output the binary to /go/bin/app2
   RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/app2 ./path/to/package2
   ```

Adjust the paths and package names accordingly based on project structure. I do not have much experience with Docker, but can test this out provided I know which option works for the project. Let me know.

**Comment by pallasite99** [comment]
@shukra-in-spirit I have made the changes here which seem to have worked on a debug branch:

https://github.com/rog-golang-buddies/dev-buddy/pull/6

Let me know if this is acceptable so that I can remove some debug statements and my branch from the CI pipeline and submit for review.
